DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS user_oauth_provider CASCADE;
DROP TABLE IF EXISTS refresh_token CASCADE;
DROP TABLE IF EXISTS email_verification CASCADE;
DROP TABLE IF EXISTS task_notification CASCADE;
DROP TABLE IF EXISTS task_category CASCADE;
DROP TABLE IF EXISTS task_difficulty CASCADE;
DROP TABLE IF EXISTS habit CASCADE;

-- ==================== TASKS ====================
CREATE TABLE habit
(
    habit_id        UUID                        NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    cycle_length    BIGINT                      NOT NULL,
    current_streak  INTEGER                     NOT NULL,
    longest_streak  INTEGER                     NOT NULL,
    is_accepted     BOOLEAN                     NOT NULL,
    accepted_date   TIMESTAMP WITHOUT TIME ZONE,
    decline_message VARCHAR(300),
    CONSTRAINT pk_habit PRIMARY KEY (habit_id)
);

CREATE TABLE task
(
    task_id          UUID                        NOT NULL,
    title            VARCHAR(200)                NOT NULL,
    start_time       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time         TIMESTAMP WITHOUT TIME ZONE,
    category_id      INTEGER                     NOT NULL,
    difficulty_id    INTEGER                     NOT NULL,
    user_id          UUID                        NOT NULL,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    task_habit_id    UUID,
    previous_task_id UUID,
    description      VARCHAR(200),
    CONSTRAINT pk_task PRIMARY KEY (task_id)
);

CREATE TABLE task_category
(
    category_id INTEGER     NOT NULL,
    title       VARCHAR(50) NOT NULL,
    value       INTEGER     NOT NULL,
    CONSTRAINT pk_task_category PRIMARY KEY (category_id)
);

CREATE TABLE task_difficulty
(
    difficulty_id INTEGER     NOT NULL,
    title         VARCHAR(50) NOT NULL,
    value         INTEGER     NOT NULL,
    CONSTRAINT pk_task_difficulty PRIMARY KEY (difficulty_id)
);

CREATE TABLE task_notification
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    send_date TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    task_id   UUID,
    CONSTRAINT pk_task_notification PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT uc_task_previous_task
        UNIQUE (previous_task_id);

ALTER TABLE task_notification
    ADD CONSTRAINT FK_TASK_NOTIFICATION_ON_TASK
        FOREIGN KEY (task_id)
            REFERENCES task (task_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CATEGORY
        FOREIGN KEY (category_id)
            REFERENCES task_category (category_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_DIFFICULTY
        FOREIGN KEY (difficulty_id)
            REFERENCES task_difficulty (difficulty_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PREVIOUS_TASK
        FOREIGN KEY (previous_task_id)
            REFERENCES task (task_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_TASK_HABIT
        FOREIGN KEY (task_habit_id)
            REFERENCES habit (habit_id);

-- ==================== USER ====================
DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
   id uuid  NOT NULL,
   first_name varchar(100)  NOT NULL,
   last_name varchar(100)  NOT NULL,
   email varchar(320)  NOT NULL,
   password varchar(200)  NULL,
   username varchar(100)  NOT NULL,
   date_of_birth date  NULL,
   experience int  NOT NULL,
   money int  NOT NULL,
   send_budget_reports boolean  NOT NULL,
   is_profile_public boolean  NOT NULL,
   is_email_verified boolean  NOT NULL,
   CONSTRAINT pk_user PRIMARY KEY (id)
);

-- ==================== AUTH ====================
CREATE TABLE user_oauth_provider
(
    id          uuid         NOT NULL,
    user_id     uuid         NOT NULL,
    provider    varchar(255) NOT NULL,
    provider_id varchar(255) NOT NULL,
    CONSTRAINT pk_user_oauth_provider PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id         uuid         NOT NULL,
    user_id    uuid         NOT NULL,
    token      varchar(255) NOT NULL,
    issued_at  timestamp(6) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    revoked    boolean      NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE email_verification
(
    id         uuid         NOT NULL,
    user_id    uuid         NOT NULL,
    code       varchar(255) NOT NULL,
    issued_at  timestamp(6) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    revoked    boolean      NOT NULL,
    CONSTRAINT email_verification_pk PRIMARY KEY (id)
);

ALTER TABLE user_oauth_provider
    ADD CONSTRAINT user_oauth_provider_user
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT refresh_token_user
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE email_verification
    ADD CONSTRAINT email_validation_tokens_users
        FOREIGN KEY (user_id)
            REFERENCES "user" (id)
;

-- ==================== INTER-MODULE CONSTRAINTS ====================
-- TODO