DROP TABLE IF EXISTS task_notification CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS task_category CASCADE;
DROP TABLE IF EXISTS task_difficulty CASCADE;
DROP TABLE IF EXISTS habit CASCADE;
DROP TABLE IF EXISTS pomodoro_task CASCADE;


DROP TABLE IF EXISTS user_oauth_provider CASCADE;
DROP TABLE IF EXISTS refresh_token CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS invitation_status CASCADE;
DROP TABLE IF EXISTS group_type CASCADE;
DROP TABLE IF EXISTS group_request_status CASCADE;
DROP TABLE IF EXISTS group_request CASCADE;
DROP TABLE IF EXISTS group_member CASCADE;
DROP TABLE IF EXISTS group_invitation CASCADE;
DROP TABLE IF EXISTS chat_message CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;

-- ==================== TASKS ====================
CREATE TABLE habit
(
    habit_id        UUID    NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    cycle_length    BIGINT  NOT NULL,
    current_streak  INTEGER NOT NULL,
    longest_streak  INTEGER NOT NULL,
    is_accepted     BOOLEAN NOT NULL,
    accepted_date   TIMESTAMP WITHOUT TIME ZONE,
    decline_message VARCHAR(300),
    CONSTRAINT pk_habit PRIMARY KEY (habit_id)
);

CREATE TABLE task
(
    task_id          UUID                        NOT NULL,
    title            VARCHAR(200)                NOT NULL,
    start_time       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time         TIMESTAMP WITHOUT TIME ZONE,
    category_id      INTEGER                     NOT NULL,
    difficulty_id    INTEGER                     NOT NULL,
    user_id          UUID                        NOT NULL,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    task_habit_id    UUID,
    previous_task_id UUID,
    description      VARCHAR(200),
    CONSTRAINT pk_task PRIMARY KEY (task_id)
);

CREATE TABLE task_category
(
    category_id INTEGER     NOT NULL,
    title       VARCHAR(50) NOT NULL,
    value       INTEGER     NOT NULL,
    CONSTRAINT pk_task_category PRIMARY KEY (category_id)
);

CREATE TABLE task_difficulty
(
    difficulty_id INTEGER     NOT NULL,
    title         VARCHAR(50) NOT NULL,
    value         INTEGER     NOT NULL,
    CONSTRAINT pk_task_difficulty PRIMARY KEY (difficulty_id)
);

CREATE TABLE task_notification
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    send_date TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    task_id   UUID,
    CONSTRAINT pk_task_notification PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT uc_task_previous_task UNIQUE (previous_task_id);

ALTER TABLE task_notification
    ADD CONSTRAINT FK_TASK_NOTIFICATION_ON_TASK FOREIGN KEY (task_id) REFERENCES task (task_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES task_category (category_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_DIFFICULTY FOREIGN KEY (difficulty_id) REFERENCES task_difficulty (difficulty_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PREVIOUS_TASK FOREIGN KEY (previous_task_id) REFERENCES task (task_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_TASK_HABIT FOREIGN KEY (task_habit_id) REFERENCES habit (habit_id);

--- Pomodoro todo users + schemas per module

CREATE TABLE pomodoro_task
(
    pomodoro_id           UUID NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    work_cycles_needed    INTEGER,
    work_cycles_completed INTEGER,
    task_id               UUID,
    CONSTRAINT pk_pomodoro_task PRIMARY KEY (pomodoro_id)
);
-- ==================== USER ====================

CREATE TABLE user_oauth_provider
(
    id          uuid         NOT NULL,
    user_id     uuid         NOT NULL,
    provider    varchar(255) NOT NULL,
    provider_id varchar(255) NOT NULL,
    CONSTRAINT pk_user_oauth_provider PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id         uuid         NOT NULL,
    user_id    uuid         NOT NULL,
    token      varchar(255) NOT NULL,
    issued_at  timestamp(6) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    revoked    boolean      NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id                  uuid         NOT NULL,
    first_name          varchar(100) NOT NULL,
    last_name           varchar(100) NOT NULL,
    email               varchar(320) NOT NULL,
    password            varchar(200) NULL,
    username            varchar(100) NOT NULL,
    date_of_birth       date         NULL,
    experience          int          NOT NULL,
    money               int          NOT NULL,
    send_budget_reports boolean      NOT NULL,
    is_profile_public   boolean      NOT NULL,
    is_email_verified   boolean      NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE user_oauth_provider
    ADD CONSTRAINT user_oauth_provider_user
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT refresh_token_user
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

-- ==================== INTER-MODULE CONSTRAINTS ====================
-- TODO

-- ==================== GROUPS ====================
CREATE TABLE chat_message
(
    message_id   UUID         NOT NULL,
    is_important BOOLEAN      NOT NULL,
    send_at      TIMESTAMP WITHOUT TIME ZONE,
    group_id     UUID         NOT NULL,
    content      VARCHAR(255) NOT NULL,
    sender_id    UUID         NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (message_id)
);

CREATE TABLE "group"
(
    group_id              UUID        NOT NULL,
    join_code             VARCHAR(20) NOT NULL,
    admin_id              UUID        NOT NULL,
    group_currency_symbol CHAR        NOT NULL,
    members_limit         INTEGER     NOT NULL,
    group_type_id         INTEGER     NOT NULL,
    CONSTRAINT pk_group PRIMARY KEY (group_id)
);

CREATE TABLE group_invitation
(
    group_invitation_id  UUID                        NOT NULL,
    group_id             UUID                        NOT NULL,
    user_id              UUID                        NOT NULL,
    expires_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    mail_sent_at         TIMESTAMP WITHOUT TIME ZONE,
    link                 VARCHAR(200)                NOT NULL,
    invitation_status_id INTEGER                     NOT NULL,
    CONSTRAINT pk_group_invitation PRIMARY KEY (group_invitation_id)
);

CREATE TABLE group_member
(
    group_member_id    UUID                        NOT NULL,
    group_id           UUID                        NOT NULL,
    user_id            UUID                        NOT NULL,
    joined_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    left_at            TIMESTAMP WITHOUT TIME ZONE,
    group_money        INTEGER                     NOT NULL,
    total_earned_money INTEGER                     NOT NULL,
    CONSTRAINT pk_group_member PRIMARY KEY (group_member_id)
);

CREATE TABLE group_request
(
    group_request_id UUID    NOT NULL,
    user_id          UUID    NOT NULL,
    group_id         UUID    NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    status_id        INTEGER NOT NULL,
    CONSTRAINT pk_group_request PRIMARY KEY (group_request_id)
);

CREATE TABLE group_request_status
(
    group_request_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                   VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_group_request_status PRIMARY KEY (group_request_status_id)
);

CREATE TABLE group_type
(
    group_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_group_type PRIMARY KEY (group_type_id)
);

CREATE TABLE invitation_status
(
    invitation_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_invitation_status PRIMARY KEY (invitation_status_id)
);

ALTER TABLE "group"
    ADD CONSTRAINT uc_group_join_code UNIQUE (join_code);

ALTER TABLE chat_message
    ADD CONSTRAINT FK_CHAT_MESSAGE_ON_GROUP FOREIGN KEY (group_id) REFERENCES "group" (group_id);

ALTER TABLE chat_message
    ADD CONSTRAINT FK_CHAT_MESSAGE_ON_SENDER FOREIGN KEY (sender_id) REFERENCES group_member (group_member_id);

ALTER TABLE group_invitation
    ADD CONSTRAINT FK_GROUP_INVITATION_ON_GROUP FOREIGN KEY (group_id) REFERENCES "group" (group_id);

ALTER TABLE group_invitation
    ADD CONSTRAINT FK_GROUP_INVITATION_ON_INVITATION_STATUS FOREIGN KEY (invitation_status_id) REFERENCES invitation_status (invitation_status_id);

ALTER TABLE group_member
    ADD CONSTRAINT FK_GROUP_MEMBER_ON_GROUP FOREIGN KEY (group_id) REFERENCES "group" (group_id);

ALTER TABLE "group"
    ADD CONSTRAINT FK_GROUP_ON_GROUP_TYPE FOREIGN KEY (group_type_id) REFERENCES group_type (group_type_id);

ALTER TABLE group_request
    ADD CONSTRAINT FK_GROUP_REQUEST_ON_GROUP FOREIGN KEY (group_id) REFERENCES "group" (group_id);

ALTER TABLE group_request
    ADD CONSTRAINT FK_GROUP_REQUEST_ON_STATUS FOREIGN KEY (status_id) REFERENCES group_request_status (group_request_status_id);